@php
    $selectedIcon = $selectedIcon ?? '';
    $iconGroups = [
        'Common / General' => [
            ['fa-solid fa-house', 'house'],
            ['fa-solid fa-user', 'user'],
            ['fa-solid fa-users', 'users'],
            ['fa-solid fa-user-plus', 'user-plus'],
            ['fa-solid fa-check', 'check'],
            ['fa-solid fa-check-double', 'check-double'],
            ['fa-solid fa-xmark', 'xmark'],
            ['fa-solid fa-plus', 'plus'],
            ['fa-solid fa-minus', 'minus'],
            ['fa-solid fa-search', 'search'],
            ['fa-solid fa-gear', 'gear'],
            ['fa-solid fa-gears', 'gears'],
            ['fa-solid fa-lock', 'lock'],
            ['fa-solid fa-unlock', 'unlock'],
            ['fa-solid fa-key', 'key'],
            ['fa-solid fa-eye', 'eye'],
            ['fa-solid fa-eye-slash', 'eye-slash'],
            ['fa-solid fa-trash', 'trash'],
            ['fa-solid fa-pen', 'pen'],
            ['fa-solid fa-pencil', 'pencil'],
            ['fa-solid fa-envelope', 'envelope'],
            ['fa-solid fa-phone', 'phone'],
            ['fa-solid fa-bell', 'bell'],
            ['fa-solid fa-calendar', 'calendar'],
            ['fa-solid fa-star', 'star'],
            ['fa-solid fa-heart', 'heart'],
            ['fa-solid fa-share', 'share'],
            ['fa-solid fa-link', 'link'],
            ['fa-solid fa-paper-plane', 'paper-plane'],
            ['fa-solid fa-circle-info', 'info'],
            ['fa-solid fa-circle-exclamation', 'warning'],
            ['fa-solid fa-circle-check', 'success'],
        ],
        'Objects / Items' => [
            ['fa-solid fa-cart-shopping', 'cart-shopping'],
            ['fa-solid fa-bag-shopping', 'bag-shopping'],
            ['fa-solid fa-gift', 'gift'],
            ['fa-solid fa-camera', 'camera'],
            ['fa-solid fa-camera-retro', 'camera-retro'],
            ['fa-solid fa-video', 'video'],
            ['fa-solid fa-music', 'music'],
            ['fa-solid fa-headphones', 'headphones'],
            ['fa-solid fa-microphone', 'microphone'],
            ['fa-solid fa-book', 'book'],
            ['fa-solid fa-newspaper', 'newspaper'],
            ['fa-solid fa-money-bill', 'money-bill'],
            ['fa-solid fa-credit-card', 'credit-card'],
            ['fa-solid fa-wallet', 'wallet'],
            ['fa-solid fa-briefcase', 'briefcase'],
            ['fa-solid fa-trophy', 'trophy'],
            ['fa-solid fa-medal', 'medal'],
            ['fa-solid fa-award', 'award'],
            ['fa-solid fa-rocket', 'rocket'],
            ['fa-solid fa-satellite', 'satellite'],
            ['fa-solid fa-shield', 'shield'],
            ['fa-solid fa-flag', 'flag'],
            ['fa-solid fa-bomb', 'bomb'],
            ['fa-solid fa-anchor', 'anchor'],
            ['fa-solid fa-compass', 'compass'],
            ['fa-solid fa-map', 'map'],
            ['fa-solid fa-globe', 'globe'],
            ['fa-solid fa-umbrella', 'umbrella'],
        ],
        'Places / Buildings' => [
            ['fa-solid fa-building', 'building'],
            ['fa-solid fa-store', 'store'],
            ['fa-solid fa-hotel', 'hotel'],
            ['fa-solid fa-hospital', 'hospital'],
            ['fa-solid fa-school', 'school'],
            ['fa-solid fa-university', 'university'],
            ['fa-solid fa-mosque', 'mosque'],
            ['fa-solid fa-kaaba', 'kaaba'],
            ['fa-solid fa-church', 'church'],
            ['fa-solid fa-synagogue', 'synagogue'],
            ['fa-solid fa-vihara', 'vihara'],
            ['fa-solid fa-torii-gate', 'torii-gate'],
            ['fa-solid fa-place-of-worship', 'place-of-worship'],
            ['fa-solid fa-city', 'city'],
            ['fa-solid fa-mountain', 'mountain'],
            ['fa-solid fa-tree', 'tree'],
            ['fa-solid fa-tent', 'tent'],
            ['fa-solid fa-landmark', 'landmark'],
        ],
        'Transport / Motion' => [
            ['fa-solid fa-car', 'car'],
            ['fa-solid fa-bus', 'bus'],
            ['fa-solid fa-train', 'train'],
            ['fa-solid fa-plane', 'plane'],
            ['fa-solid fa-truck', 'truck'],
            ['fa-solid fa-motorcycle', 'motorcycle'],
            ['fa-solid fa-bicycle', 'bicycle'],
            ['fa-solid fa-ship', 'ship'],
            ['fa-solid fa-helicopter', 'helicopter'],
        ],
        'Electronics / Digital' => [
            ['fa-solid fa-desktop', 'desktop'],
            ['fa-solid fa-laptop', 'laptop'],
            ['fa-solid fa-tablet', 'tablet'],
            ['fa-solid fa-mobile', 'mobile'],
            ['fa-solid fa-tv', 'tv'],
            ['fa-solid fa-gamepad', 'gamepad'],
            ['fa-solid fa-server', 'server'],
            ['fa-solid fa-database', 'database'],
            ['fa-solid fa-wifi', 'wifi'],
            ['fa-solid fa-terminal', 'terminal'],
            ['fa-solid fa-code', 'code'],
            ['fa-solid fa-microchip', 'microchip'],
            ['fa-solid fa-mouse', 'mouse'],
        ],
        'Food / Health' => [
            ['fa-solid fa-utensils', 'utensils'],
            ['fa-solid fa-mug-hot', 'mug-hot'],
            ['fa-solid fa-pizza-slice', 'pizza-slice'],
            ['fa-solid fa-hamburger', 'hamburger'],
            ['fa-solid fa-ice-cream', 'ice-cream'],
            ['fa-solid fa-flask', 'flask'],
            ['fa-solid fa-heart-pulse', 'heart-pulse'],
            ['fa-solid fa-stethoscope', 'stethoscope'],
            ['fa-solid fa-pills', 'pills'],
        ],
        'Nature / Animals' => [
            ['fa-solid fa-paw', 'paw'],
            ['fa-solid fa-cat', 'cat'],
            ['fa-solid fa-dog', 'dog'],
            ['fa-solid fa-horse', 'horse'],
            ['fa-solid fa-fish', 'fish'],
            ['fa-solid fa-dove', 'dove'],
            ['fa-solid fa-spider', 'spider'],
            ['fa-solid fa-bug', 'bug'],
            ['fa-solid fa-leaf', 'leaf'],
            ['fa-solid fa-fire', 'fire'],
            ['fa-solid fa-sun', 'sun'],
            ['fa-solid fa-moon', 'moon'],
            ['fa-solid fa-snowflake', 'snowflake'],
        ],
        'Brands' => [
            ['fa-brands fa-facebook', 'facebook'],
            ['fa-brands fa-twitter', 'twitter'],
            ['fa-brands fa-instagram', 'instagram'],
            ['fa-brands fa-youtube', 'youtube'],
            ['fa-brands fa-linkedin', 'linkedin'],
            ['fa-brands fa-github', 'github'],
            ['fa-brands fa-whatsapp', 'whatsapp'],
            ['fa-brands fa-telegram', 'telegram'],
            ['fa-brands fa-tiktok', 'tiktok'],
            ['fa-brands fa-snapchat', 'snapchat'],
            ['fa-brands fa-reddit', 'reddit'],
            ['fa-brands fa-discord', 'discord'],
            ['fa-brands fa-slack', 'slack'],
            ['fa-brands fa-wordpress', 'wordpress'],
            ['fa-brands fa-apple', 'apple'],
            ['fa-brands fa-android', 'android'],
            ['fa-brands fa-windows', 'windows'],
            ['fa-brands fa-linux', 'linux'],
            ['fa-brands fa-google', 'google'],
            ['fa-brands fa-amazon', 'amazon'],
            ['fa-brands fa-paypal', 'paypal'],
            ['fa-brands fa-stripe', 'stripe'],
            ['fa-brands fa-spotify', 'spotify'],
            ['fa-brands fa-playstation', 'playstation'],
            ['fa-brands fa-xbox', 'xbox'],
            ['fa-brands fa-steam', 'steam'],
            ['fa-brands fa-twitch', 'twitch'],
            ['fa-brands fa-behance', 'behance'],
            ['fa-brands fa-dribbble', 'dribbble'],
            ['fa-brands fa-bilibili', 'bilibili'],
            ['fa-brands fa-medium', 'medium'],
            ['fa-brands fa-quora', 'quora'],
            ['fa-brands fa-pinterest', 'pinterest'],
            ['fa-brands fa-skype', 'skype'],
            ['fa-brands fa-vimeo', 'vimeo'],
            ['fa-brands fa-weibo', 'weibo'],
            ['fa-brands fa-weixin', 'weixin'],
            ['fa-brands fa-line', 'line'],
            ['fa-brands fa-itunes', 'itunes'],
            ['fa-brands fa-google-play', 'google-play'],
            ['fa-brands fa-bitcoin', 'bitcoin'],
            ['fa-brands fa-ethereum', 'ethereum'],
            ['fa-brands fa-cloudflare', 'cloudflare'],
            ['fa-brands fa-digital-ocean', 'digital-ocean'],
            ['fa-brands fa-docker', 'docker'],
        ],
    ];
@endphp

@foreach ($iconGroups as $groupLabel => $icons)
    <optgroup label="{{ $groupLabel }}">
        @foreach ($icons as [$value, $label])
            <option value="{{ $value }}" data-icon="{{ $value }}">{{ $label }}</option>
        @endforeach
    </optgroup>
@endforeach
