@extends('theme::layouts.master')
@section('content')
@include('theme::ads.partials.workspace_styles')
<main class="ads-workspace" data-ads-workspace data-initial-empty="{{ $sites->isEmpty() ? 'true' : 'false' }}" data-deleted="{{ __('messages.deleted_successfully') }}" data-delete-error="{{ __('messages.ads_delete_failed') }}">
    <header class="ads-workspace__hero"><div><span class="ads-workspace__eyebrow">{{ __('messages.exvisit') }}</span><h1 class="ads-workspace__title">{{ __('messages.list') }} {{ __('messages.exvisit') }}</h1><p class="ads-workspace__copy">{{ __('messages.ctevbtexp') }}</p></div><div class="ads-workspace__actions"><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('visits.surf') }}" target="SurfWindow" onclick="window.open(this.href,'SurfWindow','width=1024,height=768');return false"><i class="fa fa-exchange" aria-hidden="true"></i>{{ __('messages.exvisit') }}</a><a class="ads-workspace__button" href="{{ route('ads.promote', ['p' => 'exchange']) }}"><i class="fa fa-plus" aria-hidden="true"></i>{{ __('messages.add') }}</a></div></header>
    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    <section class="ads-workspace__stats" aria-label="{{ __('messages.statistics') }}"><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.total') }}</span><span class="ads-workspace__stat-value" data-ads-count>{{ $sites->count() }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.active') }}</span><span class="ads-workspace__stat-value">{{ $sites->where('statu', 1)->count() }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.ptvysa') }}</span><span class="ads-workspace__stat-value">{{ number_format((float) $user->vu) }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.yshbv') }}</span><span class="ads-workspace__stat-value">{{ number_format((int) $visits) }}</span></div></section>
    <section class="ads-workspace__panel"><div class="ads-workspace__toolbar"><input class="ads-workspace__search" type="search" data-ads-search aria-label="{{ __('messages.btn_search') }}" placeholder="{{ __('messages.btn_search') }} {{ __('messages.exvisit') }}"><div class="ads-workspace__filters" role="group" aria-label="{{ __('messages.status') }}"><button class="ads-workspace__filter is-active" type="button" data-ads-filter="all" aria-pressed="true">{{ __('messages.all') }}</button><button class="ads-workspace__filter" type="button" data-ads-filter="active" aria-pressed="false">{{ __('messages.active') }}</button><button class="ads-workspace__filter" type="button" data-ads-filter="paused" aria-pressed="false">{{ __('messages.smart_status_paused') }}</button></div><span class="ads-workspace__status"><span data-ads-count>{{ $sites->count() }}</span> {{ __('messages.total') }}</span></div>
      <div class="ads-workspace__list">
      @foreach($sites as $site)
        @php($isActive = (int) $site->statu === 1)
        <article class="ads-workspace__item" data-ads-item data-status="{{ $isActive ? 'active' : 'paused' }}" data-search="{{ $site->name }} {{ $site->url }}">
          <div class="ads-workspace__identity"><h2 class="ads-workspace__name">{{ $site->name }}</h2><p class="ads-workspace__sub">#{{ $site->id }} · <a href="{{ $site->url }}" target="_blank" rel="noopener noreferrer">{{ parse_url($site->url, PHP_URL_HOST) }}</a></p></div>
          <div class="ads-workspace__metric">{{ number_format((int) $site->vu) }}<span class="ads-workspace__metric-label">{{ __('messages.views') }}</span></div><div class="ads-workspace__metric">{{ ['1' => '10s', '2' => '20s', '3' => '30s', '4' => '60s'][(string) $site->tims] ?? '10s' }}<span class="ads-workspace__metric-label">{{ __('messages.duration') }}</span></div>
          <div class="ads-workspace__row-actions"><span class="ads-workspace__badge {{ $isActive ? 'ads-workspace__badge--active' : 'ads-workspace__badge--paused' }}">{{ $isActive ? __('messages.active') : __('messages.smart_status_paused') }}</span><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('visits.edit', $site->id) }}" aria-label="{{ __('messages.edit') }}"><i class="fa fa-edit" aria-hidden="true"></i></a><form action="{{ route('visits.destroy', $site->id) }}" method="POST" data-ajax-delete data-confirm="{{ __('messages.confirm_delete_visit') }}">@csrf @method('DELETE')<button class="ads-workspace__button ads-workspace__button--danger" type="submit" aria-label="{{ __('messages.delete') }}"><i class="fa fa-trash" aria-hidden="true"></i></button></form></div>
        </article>
      @endforeach
      <div class="ads-workspace__empty" data-ads-empty hidden>{{ __('messages.no_results') }}</div>
      @if($sites->isEmpty())<div class="ads-workspace__empty">{{ __('messages.no_results') }} · <a href="{{ route('ads.promote', ['p' => 'exchange']) }}">{{ __('messages.add') }}</a></div>@endif
      </div></section><div class="ads-workspace__toast" data-ads-toast role="status" aria-live="polite"></div>
</main>
@include('theme::ads.partials.workspace_scripts')
@endsection
