@extends('theme::layouts.master')
@section('content')
@include('theme::ads.partials.workspace_styles')
<main class="ads-workspace" data-ads-workspace data-initial-empty="{{ $banners->isEmpty() ? 'true' : 'false' }}" data-deleted="{{ __('messages.deleted_successfully') }}" data-delete-error="{{ __('messages.ads_delete_failed') }}" data-copied="{{ __('messages.copied') }}">
    <header class="ads-workspace__hero"><div><span class="ads-workspace__eyebrow">{{ __('messages.advertising') }}</span><h1 class="ads-workspace__title">{{ __('messages.list') }} {{ __('messages.bannads') }}</h1><p class="ads-workspace__copy">{{ __('messages.yhtierbpyaci') }}</p></div><div class="ads-workspace__actions"><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('legacy.state', ['ty' => 'banner', 'st' => 'vu']) }}"><i class="fa fa-chart-line" aria-hidden="true"></i>{{ __('messages.statistics') }}</a><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('legacy.b_code') }}"><i class="fa fa-code" aria-hidden="true"></i>{{ __('messages.codes') }}</a><a class="ads-workspace__button" href="{{ route('ads.promote', ['p' => 'banners']) }}"><i class="fa fa-plus" aria-hidden="true"></i>{{ __('messages.add') }}</a></div></header>
    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    <section class="ads-workspace__stats" aria-label="{{ __('messages.statistics') }}"><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.total') }}</span><span class="ads-workspace__stat-value" data-ads-count>{{ $banners->count() }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.active') }}</span><span class="ads-workspace__stat-value" data-active-count>{{ $banners->where('statu', 1)->count() }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.you_have') }} {{ __('messages.ptvyba') }}</span><span class="ads-workspace__stat-value">{{ number_format((float) $user->nvu) }}</span></div></section>
    <section class="ads-workspace__panel"><div class="ads-workspace__toolbar"><input class="ads-workspace__search" type="search" data-ads-search aria-label="{{ __('messages.btn_search') }}" placeholder="{{ __('messages.btn_search') }} {{ __('messages.bannads') }}"><div class="ads-workspace__filters" role="group" aria-label="{{ __('messages.status') }}"><button class="ads-workspace__filter is-active" type="button" data-ads-filter="all" aria-pressed="true">{{ __('messages.all') }}</button><button class="ads-workspace__filter" type="button" data-ads-filter="active" aria-pressed="false">{{ __('messages.active') }}</button><button class="ads-workspace__filter" type="button" data-ads-filter="paused" aria-pressed="false">{{ __('messages.smart_status_paused') }}</button></div><span class="ads-workspace__status"><span data-ads-visible-count>{{ $banners->count() }}</span> {{ __('messages.total') }}</span></div>
      <div class="ads-workspace__list">
      @foreach($banners as $banner)
        @php($isActive = (int) $banner->statu === 1)
        <article class="ads-workspace__item" data-ads-item data-status="{{ $isActive ? 'active' : 'paused' }}" data-search="{{ $banner->name }} {{ $banner->url }} {{ $banner->px }}">
          <div class="ads-workspace__identity"><h2 class="ads-workspace__name">{{ $banner->name }}</h2><p class="ads-workspace__sub">#{{ $banner->id }} · <a href="{{ $banner->url }}" target="_blank" rel="noopener noreferrer">{{ parse_url($banner->url, PHP_URL_HOST) }}</a></p><div class="ads-workspace__heatmap">@include('theme::partials.ads.mini_heatmap', ['heatmap' => $banner->heatmap])</div></div>
          <a class="ads-workspace__metric" href="{{ route('legacy.state', ['ty' => 'banner', 'id' => $banner->id]) }}">{{ number_format((int) $banner->vu) }}<span class="ads-workspace__metric-label">{{ __('messages.banner_impressions') }}</span></a><a class="ads-workspace__metric" href="{{ route('legacy.state', ['ty' => 'vu', 'id' => $banner->id]) }}">{{ number_format((int) $banner->clik) }}<span class="ads-workspace__metric-label">{{ __('messages.clicks') }}</span></a><div class="ads-workspace__metric">{{ $banner->px }}<span class="ads-workspace__metric-label">{{ __('messages.size') }}</span></div>
          <div class="ads-workspace__row-actions"><span class="ads-workspace__badge {{ $isActive ? 'ads-workspace__badge--active' : 'ads-workspace__badge--paused' }}">{{ $isActive ? __('messages.active') : __('messages.smart_status_paused') }}</span><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('ads.banners.edit', $banner->id) }}" aria-label="{{ __('messages.edit') }}"><i class="fa fa-edit" aria-hidden="true"></i></a><form action="{{ route('ads.banners.destroy', $banner->id) }}" method="POST" data-ajax-delete data-confirm="{{ __('messages.confirm_delete_banner') }}">@csrf @method('DELETE')<button class="ads-workspace__button ads-workspace__button--danger" type="submit" aria-label="{{ __('messages.delete_banner') }}"><i class="fa fa-trash" aria-hidden="true"></i></button></form></div>
        </article>
      @endforeach
      <div class="ads-workspace__empty" data-ads-empty hidden>{{ __('messages.no_results') }}</div>
      @if($banners->isEmpty())<div class="ads-workspace__empty">{{ __('messages.no_results') }} · <a href="{{ route('ads.promote', ['p' => 'banners']) }}">{{ __('messages.add') }}</a></div>@endif
      </div></section><div class="ads-workspace__toast" data-ads-toast role="status" aria-live="polite"></div>
</main>
@include('theme::ads.partials.workspace_scripts')
@endsection
