blank_issues_enabled: false
contact_links:
  - name: MYADS Documentation & Support
    url: https://github.com/mrghozzi/myads#readme
    about: Read official documentation and guides for MYADS v4.4.6
