@extends('theme::layouts.master')
@section('content')
@include('theme::ads.partials.workspace_styles')
<main class="ads-workspace" data-ads-workspace data-initial-empty="{{ $smartAds->isEmpty() ? 'true' : 'false' }}" data-deleted="{{ __('messages.smart_ad_deleted') }}" data-delete-error="{{ __('messages.ads_delete_failed') }}" data-copied="{{ __('messages.copied') }}">
    <header class="ads-workspace__hero"><div><span class="ads-workspace__eyebrow">{{ __('messages.advertising') }}</span><h1 class="ads-workspace__title">{{ __('messages.smart_ads') }}</h1><p class="ads-workspace__copy">{{ __('messages.smart_index_byline') }}</p></div><div class="ads-workspace__actions"><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('legacy.state', ['ty' => 'smart', 'st' => 'vu']) }}"><i class="fa fa-chart-line" aria-hidden="true"></i>{{ __('messages.statistics') }}</a><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('ads.smart.code') }}"><i class="fa fa-code" aria-hidden="true"></i>{{ __('messages.code') }}</a><a class="ads-workspace__button" href="{{ route('ads.smart.create') }}"><i class="fa fa-plus" aria-hidden="true"></i>{{ __('messages.smart_create_ad') }}</a></div></header>
    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    @if(session('warning'))<div class="alert alert-warning" role="status">{{ session('warning') }}</div>@endif
    <section class="ads-workspace__stats" aria-label="{{ __('messages.statistics') }}"><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.total') }}</span><span class="ads-workspace__stat-value" data-ads-count>{{ $smartAds->count() }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.active') }}</span><span class="ads-workspace__stat-value">{{ $smartAds->where('statu', 1)->count() }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.smart_impressions_label') }}</span><span class="ads-workspace__stat-value">{{ number_format((int) $smartAds->sum('impressions')) }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.smart_clicks_label') }}</span><span class="ads-workspace__stat-value">{{ number_format((int) $smartAds->sum('clicks')) }}</span></div><div class="ads-workspace__stat"><span class="ads-workspace__stat-label">{{ __('messages.smart_ad_credits') }}</span><span class="ads-workspace__stat-value">{{ number_format((float) $user->nsmart, 2) }}</span></div></section>
    <section class="ads-workspace__panel"><div class="ads-workspace__toolbar"><input class="ads-workspace__search" type="search" data-ads-search aria-label="{{ __('messages.btn_search') }}" placeholder="{{ __('messages.btn_search') }} {{ __('messages.smart_ads') }}"><div class="ads-workspace__filters" role="group" aria-label="{{ __('messages.status') }}"><button class="ads-workspace__filter is-active" type="button" data-ads-filter="all" aria-pressed="true">{{ __('messages.all') }}</button><button class="ads-workspace__filter" type="button" data-ads-filter="active" aria-pressed="false">{{ __('messages.active') }}</button><button class="ads-workspace__filter" type="button" data-ads-filter="paused" aria-pressed="false">{{ __('messages.smart_status_paused') }}</button></div><span class="ads-workspace__status"><span data-ads-count>{{ $smartAds->count() }}</span> {{ __('messages.total') }}</span></div>
      <div class="ads-workspace__list">
      @foreach($smartAds as $smartAd)
        @php($isActive = (int) $smartAd->statu === 1)
        <article class="ads-workspace__item" data-ads-item data-status="{{ $isActive ? 'active' : 'paused' }}" data-search="{{ $smartAd->displayTitle() }} {{ $smartAd->displayDescription() }} {{ $smartAd->landing_url }} {{ $smartAd->manual_keywords }} {{ $smartAd->extracted_keywords }}" style="grid-template-columns:minmax(0,1.3fr) repeat(2,minmax(90px,.55fr)) auto">
          <div class="ads-workspace__identity"><h2 class="ads-workspace__name">{{ $smartAd->displayTitle() }}</h2><p class="ads-workspace__sub">#{{ $smartAd->id }} · <a href="{{ $smartAd->landing_url }}" target="_blank" rel="noopener noreferrer">{{ parse_url($smartAd->landing_url, PHP_URL_HOST) }}</a></p><p class="ads-workspace__sub">{{ \Illuminate\Support\Str::limit($smartAd->displayDescription(), 150) }}</p><p class="ads-workspace__sub">{{ __('messages.smart_target_countries_label') }}: {{ \App\Support\SmartAdTargeting::formatTargets($smartAd->targetCountries()) }} · {{ __('messages.smart_target_devices_label') }}: {{ \App\Support\SmartAdTargeting::formatTargets($smartAd->targetDevices()) }}</p></div>
          <a class="ads-workspace__metric" href="{{ route('legacy.state', ['ty' => 'smart', 'id' => $smartAd->id]) }}">{{ number_format((int) $smartAd->impressions) }}<span class="ads-workspace__metric-label">{{ __('messages.smart_impressions_label') }}</span></a><a class="ads-workspace__metric" href="{{ route('legacy.state', ['ty' => 'smart_click', 'id' => $smartAd->id]) }}">{{ number_format((int) $smartAd->clicks) }}<span class="ads-workspace__metric-label">{{ __('messages.smart_clicks_label') }}</span></a>
          <div class="ads-workspace__row-actions"><span class="ads-workspace__badge {{ $isActive ? 'ads-workspace__badge--active' : 'ads-workspace__badge--paused' }}">{{ $isActive ? __('messages.active') : __('messages.smart_status_paused') }}</span><a class="ads-workspace__button ads-workspace__button--soft" href="{{ route('ads.smart.edit', $smartAd->id) }}" aria-label="{{ __('messages.edit') }}"><i class="fa fa-edit" aria-hidden="true"></i></a><form action="{{ route('ads.smart.destroy', $smartAd->id) }}" method="POST" data-ajax-delete data-confirm="{{ __('messages.smart_delete_confirm') }}">@csrf @method('DELETE')<button class="ads-workspace__button ads-workspace__button--danger" type="submit" aria-label="{{ __('messages.delete') }}"><i class="fa fa-trash" aria-hidden="true"></i></button></form></div>
        </article>
      @endforeach
      <div class="ads-workspace__empty" data-ads-empty hidden>{{ __('messages.no_results') }}</div>
      @if($smartAds->isEmpty())<div class="ads-workspace__empty"><h2>{{ __('messages.smart_empty_title') }}</h2><p>{{ __('messages.smart_empty_desc') }}</p><a class="ads-workspace__button" href="{{ route('ads.smart.create') }}">{{ __('messages.smart_create_ad') }}</a></div>@endif
      </div></section><div class="ads-workspace__toast" data-ads-toast role="status" aria-live="polite"></div>
</main>
@include('theme::ads.partials.workspace_scripts')
@endsection
