<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\DirectoryCategory;
use App\Models\Directory;
use App\Models\Short;
use App\Models\Status;

class DirectoryController extends Controller
{
    public function index()
    {
        // Load categories separately so they show even if activities fail
        try {
            $categories = DirectoryCategory::where('sub', 0)
                ->where('statu', 1)
                ->orderBy('ordercat', 'asc')
                ->get();
        } catch (\Throwable $e) {
            $categories = collect();
        }

        try {
            $activities = Status::where('s_type', 1)
                ->where('date', '<', time())
                ->orderBy('date', 'desc')
                ->paginate(15);

            $directoryIds = $activities->pluck('tp_id')->filter()->unique();
            $directories = Directory::whereIn('id', $directoryIds)->get()->keyBy('id');
            foreach ($activities as $activity) {
                $activity->related_content = $directories->get($activity->tp_id);
            }
        } catch (\Throwable $e) {
            $activities = new \Illuminate\Pagination\LengthAwarePaginator([], 0, 15);
        }

        if (request()->ajax()) {
            $html = view('theme::partials.ajax.activities', compact('activities'))->render();
            return response()->json([
                'html' => $html,
                'next_page_url' => $activities->nextPageUrl()
            ]);
        }

        return view('theme::directory.index', compact('categories', 'activities'));
    }

    public function category($id)
    {
        try {
            $category = DirectoryCategory::findOrFail($id);
            
            // Get subcategories
            $subCategories = DirectoryCategory::where('sub', $id)
                ->where('statu', 1)
                ->orderBy('ordercat', 'asc')
                ->get();

            $directoryIds = Directory::where('cat', $id)
                ->where('statu', 1)
                ->pluck('id');

            $activities = Status::where('s_type', 1)
                ->where('date', '<', time())
                ->whereIn('tp_id', $directoryIds)
                ->orderBy('date', 'desc')
                ->paginate(15);

            $directories = Directory::whereIn('id', $directoryIds)->get()->keyBy('id');
            foreach ($activities as $activity) {
                $activity->related_content = $directories->get($activity->tp_id);
            }
        } catch (\Throwable $e) {
            abort(404);
        }

        if (request()->ajax()) {
            $html = view('theme::partials.ajax.activities', compact('activities'))->render();
            return response()->json([
                'html' => $html,
                'next_page_url' => $activities->nextPageUrl()
            ]);
        }

        return view('theme::directory.category', compact('category', 'subCategories', 'activities'));
    }

    public function show($id)
    {
        // Reject non-numeric IDs (prevents /directory/store, /directory/ads etc.)
        if (!is_numeric($id)) {
            abort(404);
        }

        try {
            $listing = Directory::findOrFail($id);
            $activity = Status::where('s_type', 1)
                ->where('tp_id', $listing->id)
                ->first();

            if (!$activity) {
                return abort(404);
            }

            $activity->related_content = $listing;

            return view('theme::directory.show', compact('listing', 'activity'));
        } catch (\Throwable $e) {
            abort(404);
        }
    }

    public function showShort($id)
    {
        return redirect()->route('directory.show', $id);
    }

    public function redirectShort($hash)
    {
        // Handle site-{hash} format from old system
        if (strpos($hash, 'site-') === 0) {
            $realHash = substr($hash, 5);
            
            // Try to find in Short table first
            $short = Short::where('sho', $realHash)->where('sh_type', 1)->first();
            
            if (!$short) {
                // If not found, it might be a dynamic hash not yet stored.
                // We need to find the directory entry that produces this hash.
                // This is expensive (iteration), so ideally Shorts are pre-generated.
                // For now, let's try to find it.
                // hash('crc32', $url . $id)
                // Since we don't know ID or URL, we can't reverse the hash easily.
                // BUT, if we assume the ID is passed in some other way... no.
                
                // Let's create a temporary solution:
                // If we assume we have migrated data, Short should exist.
                // If we assume new data, Short is created on store/update.
                
                // If the user is clicking a link generated by the view we just modified,
                // the view used hash('crc32', $url . $id).
                // We need to ensure that when a Directory is created/updated, a Short record is created with this hash.
                
                // Let's check if we can recover.
                // If we can't find it, maybe we should redirect to home or 404.
                return abort(404);
            }
        } else {
            $short = Short::where('sho', $hash)->where('sh_type', 1)->first();
        }

        if (!$short) {
            return abort(404);
        }

        $listing = Directory::find($short->tp_id);
        if ($listing) {
            $listing->increment('vu');
        }

        if (filter_var($short->url, FILTER_VALIDATE_URL) === false) {
            return abort(404);
        }

        return redirect($short->url);
    }

    public function create()
    {
        $categories = DirectoryCategory::where('statu', 1)
            ->orderBy('ordercat', 'asc')
            ->get();

        $mainCategories = $categories->where('sub', 0);
        $subCategories = $categories->where('sub', '!=', 0)->groupBy('sub');

        return view('theme::directory.create', compact('mainCategories', 'subCategories'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'url' => 'required|url',
            'categ' => 'required|integer',
            'txt' => 'nullable|string',
            'tag' => 'nullable|string',
        ]);

        try {
            $listing = Directory::create([
                'uid' => auth()->id(),
                'name' => $request->name,
                'url' => $request->url,
                'cat' => $request->categ,
                'txt' => $request->txt ?? '',
                'metakeywords' => $request->tag ?? '',
                'date' => time(),
                'statu' => 1,
                'vu' => 0,
            ]);

            // Create Status
            Status::create([
                'uid' => auth()->id(),
                'tp_id' => $listing->id,
                's_type' => 1,
                'date' => time(),
            ]);

            // Create Short URL record
            $hash = hash('crc32', $listing->url . $listing->id);
            Short::create([
                'uid' => auth()->id(),
                'url' => $listing->url,
                'sho' => $hash,
                'clik' => 0,
                'sh_type' => 1,
                'tp_id' => $listing->id,
            ]);

            return redirect()->route('directory.show', $listing->id)->with('success', __('WebsiteCreated'));
        } catch (\Throwable $e) {
            return redirect()->back()->withErrors(['error' => __('messages.error_occurred') . ': ' . $e->getMessage()])->withInput();
        }
    }

    public function edit($id)
    {
        $listing = Directory::findOrFail($id);

        if ($listing->uid != auth()->id() && !auth()->user()->isAdmin()) {
            return abort(403);
        }

        $categories = DirectoryCategory::where('statu', 1)
            ->orderBy('ordercat', 'asc')
            ->get();

        $mainCategories = $categories->where('sub', 0);
        $subCategories = $categories->where('sub', '!=', 0)->groupBy('sub');

        return view('theme::directory.edit', compact('listing', 'mainCategories', 'subCategories'));
    }

    public function update(Request $request, $id)
    {
        $listing = Directory::findOrFail($id);

        if ($listing->uid != auth()->id() && !auth()->user()->isAdmin()) {
            return abort(403);
        }

        $request->validate([
            'name' => 'required|string|max:255',
            'url' => 'required|url',
            'categ' => 'required|integer',
            'txt' => 'nullable|string',
            'tag' => 'nullable|string',
        ]);

        $listing->update([
            'name' => $request->name,
            'url' => $request->url,
            'cat' => $request->categ,
            'txt' => $request->txt ?? '',
            'metakeywords' => $request->tag ?? '',
        ]);

        // Update Short URL record
        $hash = hash('crc32', $listing->url . $listing->id);
        Short::updateOrCreate(
            ['tp_id' => $listing->id, 'sh_type' => 1],
            [
                'uid' => auth()->id(),
                'url' => $listing->url,
                'sho' => $hash,
            ]
        );

        return redirect()->route('directory.show', $listing->id)->with('success', __('EditWebsite'));
    }

    public function destroy(Request $request)
    {
        $id = $request->input('id');
        if (!$id) return response()->json(['error' => 'Missing ID'], 400);

        $listing = Directory::find($id);
        if (!$listing) return response()->json(['error' => 'Not found'], 404);

        if ($listing->uid != auth()->id() && !auth()->user()->isAdmin()) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }

        \Illuminate\Support\Facades\DB::transaction(function () use ($listing, $id) {
            // Delete related status
            Status::where('tp_id', $id)->where('s_type', 1)->delete();
            
            // Delete related options (comments, reactions)
            \App\Models\Option::where('o_parent', $id)->whereIn('o_type', ['d_coment', 'data_reaction'])->delete();

            // Delete listing
            $listing->delete();
        });

        return response()->json(['success' => true]);
    }
}
