<style>
.ads-workspace{--ads-bg:#f5f7fb;--ads-surface:#fff;--ads-text:#172033;--ads-muted:#64748b;--ads-border:#e2e8f0;--ads-accent:#4f46e5;--ads-accent-soft:#eef2ff;--ads-success:#12805c;--ads-warning:#b45309;--ads-danger:#b42318;color:var(--ads-text);display:grid;gap:1.25rem;margin-bottom:2rem}
body[data-theme="css_d"] .ads-workspace{--ads-bg:#151a27;--ads-surface:#202737;--ads-text:#edf2fb;--ads-muted:#a0aec0;--ads-border:#354155;--ads-accent:#a5b4fc;--ads-accent-soft:#2a3150;--ads-success:#6ee7b7;--ads-warning:#fbbf24;--ads-danger:#fca5a5}
.ads-workspace *{box-sizing:border-box}.ads-workspace__hero{align-items:center;background:radial-gradient(circle at 90% 0,rgba(99,102,241,.16),transparent 35%),var(--ads-surface);border:1px solid var(--ads-border);border-radius:22px;display:flex;flex-wrap:wrap;gap:1.5rem;justify-content:space-between;padding:clamp(1.2rem,3vw,2rem)}
.ads-workspace__eyebrow{color:var(--ads-accent);font-size:.75rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.ads-workspace__title{color:var(--ads-text);font-size:clamp(1.5rem,3vw,2.15rem);font-weight:800;letter-spacing:-.035em;margin:.35rem 0}.ads-workspace__copy{color:var(--ads-muted);margin:0;max-width:58ch}.ads-workspace__actions,.ads-workspace__tools,.ads-workspace__row-actions{align-items:center;display:flex;flex-wrap:wrap;gap:.65rem}
.ads-workspace__button{align-items:center;background:var(--ads-accent);border:1px solid var(--ads-accent);border-radius:10px;color:#fff!important;display:inline-flex;font-size:.84rem;font-weight:700;gap:.5rem;justify-content:center;min-height:42px;padding:.65rem 1rem;text-decoration:none;transition:transform .15s ease,filter .15s ease}.ads-workspace__button:hover{filter:brightness(1.07);transform:translateY(-1px)}.ads-workspace__button--soft{background:var(--ads-accent-soft);border-color:var(--ads-border);color:var(--ads-text)!important}.ads-workspace__button--danger{background:transparent;border-color:var(--ads-border);color:var(--ads-danger)!important}.ads-workspace__button:disabled{opacity:.6;pointer-events:none}
.ads-workspace__stats{display:grid;gap:.8rem;grid-template-columns:repeat(auto-fit,minmax(150px,1fr))}.ads-workspace__stat,.ads-workspace__panel,.ads-workspace__item{background:var(--ads-surface);border:1px solid var(--ads-border);border-radius:16px}.ads-workspace__stat{padding:1rem 1.1rem}.ads-workspace__stat-label{color:var(--ads-muted);display:block;font-size:.78rem;font-weight:700;margin-bottom:.25rem}.ads-workspace__stat-value{font-size:1.45rem;font-weight:800;line-height:1.2}.ads-workspace__panel{overflow:hidden}.ads-workspace__toolbar{align-items:center;border-bottom:1px solid var(--ads-border);display:flex;flex-wrap:wrap;gap:.75rem;justify-content:space-between;padding:1rem}.ads-workspace__search{background:var(--ads-bg);border:1px solid var(--ads-border);border-radius:10px;color:var(--ads-text);font:inherit;min-height:42px;min-width:min(100%,280px);padding:.6rem .8rem}.ads-workspace__filters{display:flex;flex-wrap:wrap;gap:.4rem}.ads-workspace__filter{background:transparent;border:1px solid var(--ads-border);border-radius:999px;color:var(--ads-muted);cursor:pointer;font:inherit;font-size:.78rem;padding:.45rem .75rem}.ads-workspace__filter.is-active{background:var(--ads-accent-soft);border-color:var(--ads-accent);color:var(--ads-accent);font-weight:700}
.ads-workspace__list{display:grid;gap:.75rem;padding:1rem}.ads-workspace__item{align-items:center;display:grid;gap:1rem;grid-template-columns:minmax(0,1.4fr) repeat(3,minmax(90px,.55fr)) auto;padding:1rem;transition:opacity .15s ease,transform .15s ease}.ads-workspace__item.is-removing{opacity:0;transform:translateX(10px)}.ads-workspace__identity{min-width:0}.ads-workspace__name{color:var(--ads-text);font-size:1rem;font-weight:750;margin:0 0 .25rem;overflow-wrap:anywhere}.ads-workspace__sub{color:var(--ads-muted);font-size:.8rem;margin:0;overflow-wrap:anywhere}.ads-workspace__metric{color:var(--ads-text);font-weight:750}.ads-workspace__metric-label{color:var(--ads-muted);display:block;font-size:.72rem;font-weight:600}.ads-workspace__badge{align-items:center;border-radius:999px;display:inline-flex;font-size:.73rem;font-weight:750;gap:.35rem;padding:.38rem .62rem;white-space:nowrap}.ads-workspace__badge--active{background:rgba(16,185,129,.12);color:var(--ads-success)}.ads-workspace__badge--paused{background:rgba(245,158,11,.13);color:var(--ads-warning)}.ads-workspace__empty{color:var(--ads-muted);padding:2.5rem 1rem;text-align:center}.ads-workspace__toast{background:#172033;border-radius:10px;bottom:1.25rem;color:white;inset-inline-end:1.25rem;opacity:0;padding:.8rem 1rem;pointer-events:none;position:fixed;transform:translateY(8px);transition:.2s ease;z-index:9999}.ads-workspace__toast.is-visible{opacity:1;transform:translateY(0)}.ads-workspace__status{color:var(--ads-muted);font-size:.8rem}
.ads-workspace__metric{text-decoration:none}.ads-workspace__heatmap{margin-top:.4rem;max-width:260px}
.ads-workspace__snippet{background:#0f172a;border:1px solid var(--ads-border);border-radius:12px;color:#dbeafe;display:block;font:500 .82rem/1.6 ui-monospace,SFMono-Regular,Consolas,monospace;min-height:100px;padding:1rem;resize:vertical;width:100%}.ads-workspace__code-layout{display:grid;gap:1rem;grid-template-columns:minmax(0,1.15fr) minmax(260px,.85fr)}.ads-workspace__preview{background:var(--ads-bg);border:1px dashed var(--ads-border);border-radius:12px;min-height:150px;overflow:auto;padding:1rem}.ads-workspace__item[hidden]{display:none!important}
.ads-code-workspace .widget-box,.ads-code-workspace .tab-box{background:var(--ads-surface)!important;border:1px solid var(--ads-border)!important;border-radius:16px!important;color:var(--ads-text)!important;box-shadow:none!important;padding:1.1rem!important}.ads-code-workspace .widget-box-title,.ads-code-workspace .tab-box-item-title{color:var(--ads-text)!important;font-weight:750}.ads-code-workspace .widget-box-text,.ads-code-workspace .tab-box-item-paragraph{color:var(--ads-muted)!important}.ads-code-workspace .tab-box-option{cursor:pointer}.ads-code-workspace .tab-box-option-title{color:var(--ads-text)!important}.ads-code-workspace textarea.form-control{background:var(--ads-bg)!important;border:1px solid var(--ads-border)!important;border-radius:10px!important;color:var(--ads-text)!important;min-height:90px!important}.ads-code-workspace blockquote.widget-box{overflow-wrap:anywhere}.ads-code-workspace .well{background:var(--ads-bg)!important;border:1px solid var(--ads-border)!important;border-radius:12px;padding:1rem}.ads-workspace__copy-button{background:var(--ads-accent-soft);border:1px solid var(--ads-border);border-radius:8px;color:var(--ads-text);cursor:pointer;font-family:inherit;font-size:.78rem;font-weight:700;margin-top:.5rem;padding:.45rem .7rem}
body[data-theme="css_d"] .myads-banner-code-preview{background:var(--ads-surface)!important;border-color:var(--ads-border)!important;color:var(--ads-text)!important}body[data-theme="css_d"] .myads-banner-code-preview [style*="color: #5d6488"],body[data-theme="css_d"] .ads-code-workspace [style*="color: #5d6488"]{color:var(--ads-muted)!important}.ads-code-workspace .well[style*="color: black"]{color:var(--ads-text)!important}
@media(max-width:900px){.ads-workspace__item{grid-template-columns:minmax(0,1fr) repeat(2,minmax(80px,.5fr))}.ads-workspace__row-actions{grid-column:1/-1}.ads-workspace__code-layout{grid-template-columns:1fr}}
@media(max-width:600px){.ads-workspace__item{grid-template-columns:repeat(2,minmax(0,1fr))}.ads-workspace__identity{grid-column:1/-1}.ads-workspace__metric{font-size:.9rem}.ads-workspace__actions{width:100%}.ads-workspace__button{flex:1}.ads-workspace__toolbar{align-items:stretch}.ads-workspace__search{width:100%}}
@media(prefers-reduced-motion:reduce){.ads-workspace *{scroll-behavior:auto!important;transition:none!important}}
</style>
