<script>
document.addEventListener('DOMContentLoaded',function(){
 document.querySelectorAll('[data-ads-workspace]').forEach(function(root){
  root.querySelectorAll('textarea[readonly]').forEach(function(field,index){field.removeAttribute('onclick');field.dataset.copyIndex=index;const button=document.createElement('button');button.type='button';button.className='ads-workspace__copy-button';button.textContent=root.dataset.copyLabel||'Copy';button.setAttribute('data-copy-target','[data-copy-index="'+index+'"]');field.setAttribute('data-copy-index',index);field.insertAdjacentElement('afterend',button)});
  const search=root.querySelector('[data-ads-search]'), buttons=Array.from(root.querySelectorAll('[data-ads-filter]')), empty=root.querySelector('[data-ads-empty]');let items=Array.from(root.querySelectorAll('[data-ads-item]')),filter='all';
  function apply(){const q=(search?.value||'').trim().toLocaleLowerCase();let visible=0;items.forEach(function(item){const matchText=!q||(item.dataset.search||'').toLocaleLowerCase().includes(q),matchStatus=filter==='all'||item.dataset.status===filter;item.hidden=!(matchText&&matchStatus);if(!item.hidden)visible++});root.querySelectorAll('[data-ads-count]').forEach(node=>node.textContent=items.length);root.querySelectorAll('[data-ads-visible-count]').forEach(node=>node.textContent=visible);root.querySelectorAll('[data-active-count]').forEach(node=>node.textContent=items.filter(item=>item.dataset.status==='active').length);if(empty)empty.hidden=visible!==0||(items.length===0&&root.dataset.initialEmpty==='true');}
  search?.addEventListener('input',apply);buttons.forEach(function(button){button.addEventListener('click',function(){filter=button.dataset.adsFilter;buttons.forEach(b=>{b.classList.toggle('is-active',b===button);b.setAttribute('aria-pressed',b===button?'true':'false')});apply()})});apply();
  root.addEventListener('submit',async function(event){const form=event.target.closest('form[data-ajax-delete]');if(!form)return;event.preventDefault();if(!window.confirm(form.dataset.confirm||''))return;const submit=form.querySelector('button[type="submit"]'),row=form.closest('[data-ads-item]');if(submit){submit.disabled=true;submit.dataset.label=submit.textContent;submit.textContent='…'}
   try{const response=await fetch(form.action,{method:'POST',credentials:'same-origin',headers:{'Accept':'application/json','X-Requested-With':'XMLHttpRequest','X-CSRF-TOKEN':form.querySelector('[name="_token"]')?.value||''},body:new FormData(form)});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'');row?.classList.add('is-removing');window.setTimeout(()=>{row?.remove();items=items.filter(item=>item!==row);apply()},180);toast(root,root.dataset.deleted||'');}
   catch(error){if(submit){submit.disabled=false;submit.textContent=submit.dataset.label||''}toast(root,root.dataset.deleteError||'');}
  });
  root.addEventListener('click',async function(event){const button=event.target.closest('[data-copy-target]');if(!button)return;const field=root.querySelector(button.dataset.copyTarget);if(!field)return;try{await navigator.clipboard.writeText(field.value??field.textContent);toast(root,root.dataset.copied||'')}catch(e){field.focus();field.select();document.execCommand('copy');toast(root,root.dataset.copied||'')}});
 });
 function toast(root,message){const node=root.querySelector('[data-ads-toast]');if(!node)return;node.textContent=message;node.classList.add('is-visible');clearTimeout(node._timer);node._timer=setTimeout(()=>node.classList.remove('is-visible'),2200)}
});
</script>
